const std = @import("std");
const compose = @import("compose.zig");
const t = std.testing;

test "render refuses zero plugins" {
	try t.expectError(error.NoPlugins, compose.render(t.allocator, "default", "/cfg/flake", &.{}));
}

test "golden render: one plugin" {
	const out = try compose.render(t.allocator, "default", "/home/u/.config/cogbox/instances/default/flake", &.{
		.{ .name = "panopticon", .locked_url = "github:o/panopticon/abc123?narHash=sha256-AAAA" },
	});
	defer t.allocator.free(out);

	const expected =
		"# GENERATED by 'cogbox plugin' -- DO NOT EDIT.\n" ++
		"# Regenerated from config.json (.plugins) on every plugin add/del/update.\n" ++
		"{\n" ++
		"\tdescription = \"cogbox plugin composition for instance 'default'\";\n" ++
		"\n" ++
		"\tinputs = {\n" ++
		"\t\tuser.url = \"path:/home/u/.config/cogbox/instances/default/flake\";\n" ++
		"\t\t\"p-panopticon\".url = \"github:o/panopticon/abc123?narHash=sha256-AAAA\";\n" ++
		"\t};\n" ++
		"\n" ++
		"\toutputs = { self, user, ... }@inputs: {\n" ++
		"\t\tnixosModules.default = {\n" ++
		"\t\t\timports = [\n" ++
		"\t\t\t\tinputs.\"p-panopticon\".nixosModules.\"default\"\n" ++
		"\t\t\t\tuser.nixosModules.default\n" ++
		"\t\t\t];\n" ++
		"\t\t};\n" ++
		"\t};\n" ++
		"}\n";
	try t.expectEqualStrings(expected, out);
}

test "two plugins keep config order, user module last" {
	const out = try compose.render(t.allocator, "work", "/cfg/flake", &.{
		.{ .name = "alpha", .locked_url = "path:/a?narHash=sha256-A" },
		.{ .name = "beta", .locked_url = "path:/b?narHash=sha256-B" },
	});
	defer t.allocator.free(out);

	const a_in = std.mem.indexOf(u8, out, "\"p-alpha\".url").?;
	const b_in = std.mem.indexOf(u8, out, "\"p-beta\".url").?;
	try t.expect(a_in < b_in);

	const a_imp = std.mem.indexOf(u8, out, "inputs.\"p-alpha\".nixosModules.\"default\"").?;
	const b_imp = std.mem.indexOf(u8, out, "inputs.\"p-beta\".nixosModules.\"default\"").?;
	const user_imp = std.mem.indexOf(u8, out, "user.nixosModules.default\n\t\t\t];").?;
	try t.expect(a_imp < b_imp);
	try t.expect(b_imp < user_imp);
	try t.expect(std.mem.indexOf(u8, out, "instance 'work'") != null);
}

test "non-default module attrs are emitted quoted" {
	const out = try compose.render(t.allocator, "default", "/cfg/flake", &.{
		.{ .name = "hello", .locked_url = "path:/m?narHash=sha256-M" },
		.{ .name = "extra", .locked_url = "path:/m?narHash=sha256-M", .attr = "extra" },
	});
	defer t.allocator.free(out);

	// Same flake URL twice (two modules of one flake) is fine: two pinned
	// inputs that resolve to the same store path.
	try t.expect(std.mem.indexOf(u8, out, "inputs.\"p-hello\".nixosModules.\"default\"") != null);
	try t.expect(std.mem.indexOf(u8, out, "inputs.\"p-extra\".nixosModules.\"extra\"") != null);
}

test "nix string escaping in urls and paths" {
	const out = try compose.render(t.allocator, "default", "/odd \"dir\"/flake", &.{
		.{ .name = "x", .locked_url = "path:/p?x=${q}&y=a\\b" },
	});
	defer t.allocator.free(out);

	try t.expect(std.mem.indexOf(u8, out, "path:/odd \\\"dir\\\"/flake") != null);
	try t.expect(std.mem.indexOf(u8, out, "\\${q}") != null);
	try t.expect(std.mem.indexOf(u8, out, "a\\\\b") != null);
}
