// Render and write the generated composition flake that folds every plugin's
// nixosModules.default (plus the per-instance user flake) into one module.
//
// The file is a pure function of config.json's .plugins array and is
// regenerated on every plugin mutation; cogbox-launch.sh points
// --override-input userExtensions at its directory when plugins exist.
// Plugin inputs are pinned by locked URL (rev + narHash), so evaluating the
// composition never needs the network once `nix flake archive` has run.

const std = @import("std");

pub const PluginRef = struct {
	name: []const u8,
	locked_url: []const u8,
	attr: []const u8 = "default", // nixosModules attr to import
};

pub const RenderError = error{
	NoPlugins,
	OutOfMemory,
};

/// Render the composition flake. Plugin inputs are named "p-<name>" (quoted
/// attrs) so they can never collide with `user`/`self`; the user flake is
/// always imported, last.
pub fn render(
	allocator: std.mem.Allocator,
	instance: []const u8,
	user_flake_dir: []const u8,
	plugins: []const PluginRef,
) RenderError![]u8 {
	if (plugins.len == 0) return error.NoPlugins;

	var out: std.ArrayList(u8) = .empty;
	defer out.deinit(allocator);

	try out.appendSlice(allocator, "# GENERATED by 'cogbox plugin' -- DO NOT EDIT.\n" ++
		"# Regenerated from config.json (.plugins) on every plugin add/del/update.\n" ++
		"{\n" ++
		"\tdescription = \"cogbox plugin composition for instance '");
	try out.appendSlice(allocator, instance);
	try out.appendSlice(allocator, "'\";\n\n\tinputs = {\n\t\tuser.url = \"path:");
	try appendNixString(allocator, &out, user_flake_dir);
	try out.appendSlice(allocator, "\";\n");
	for (plugins) |p| {
		try out.appendSlice(allocator, "\t\t\"p-");
		try out.appendSlice(allocator, p.name);
		try out.appendSlice(allocator, "\".url = \"");
		try appendNixString(allocator, &out, p.locked_url);
		try out.appendSlice(allocator, "\";\n");
	}
	try out.appendSlice(allocator, "\t};\n\n" ++
		"\toutputs = { self, user, ... }@inputs: {\n" ++
		"\t\tnixosModules.default = {\n" ++
		"\t\t\timports = [\n");
	for (plugins) |p| {
		try out.appendSlice(allocator, "\t\t\t\tinputs.\"p-");
		try out.appendSlice(allocator, p.name);
		try out.appendSlice(allocator, "\".nixosModules.\"");
		try out.appendSlice(allocator, p.attr);
		try out.appendSlice(allocator, "\"\n");
	}
	try out.appendSlice(allocator, "\t\t\t\tuser.nixosModules.default\n" ++
		"\t\t\t];\n" ++
		"\t\t};\n" ++
		"\t};\n" ++
		"}\n");

	return try out.toOwnedSlice(allocator);
}

/// Escape for a double-quoted nix string: `\`, `"`, and `${`.
fn appendNixString(allocator: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) !void {
	for (s, 0..) |c, i| {
		switch (c) {
			'\\' => try out.appendSlice(allocator, "\\\\"),
			'"' => try out.appendSlice(allocator, "\\\""),
			'$' => {
				if (i + 1 < s.len and s[i + 1] == '{') {
					try out.appendSlice(allocator, "\\$");
				} else {
					try out.append(allocator, c);
				}
			},
			else => try out.append(allocator, c),
		}
	}
}

/// Atomically write `rendered` as <dir>/flake.nix (mkdir -p, .tmp + rename).
/// Stale flake.lock files from earlier nix invocations are removed so the
/// locked-URL inputs are always re-resolved from the rendered file alone.
pub fn writeCompositionFlake(
	allocator: std.mem.Allocator,
	io: std.Io,
	dir: []const u8,
	rendered: []const u8,
) !void {
	const cwd = std.Io.Dir.cwd();
	try cwd.createDirPath(io, dir);

	const path = try std.fs.path.join(allocator, &.{ dir, "flake.nix" });
	defer allocator.free(path);
	const tmp_path = try std.fmt.allocPrint(allocator, "{s}.tmp", .{path});
	defer allocator.free(tmp_path);

	{
		const f = try cwd.createFile(io, tmp_path, .{ .truncate = true });
		defer f.close(io);
		var write_buf: [4096]u8 = undefined;
		var writer = f.writer(io, &write_buf);
		try writer.interface.writeAll(rendered);
		try writer.flush();
		try f.sync(io);
	}
	try cwd.rename(tmp_path, cwd, path, io);

	const lock_path = try std.fs.path.join(allocator, &.{ dir, "flake.lock" });
	defer allocator.free(lock_path);
	cwd.deleteFile(io, lock_path) catch {};
}

/// Remove the generated flake (used when the last plugin is deleted, so the
/// launcher falls back to the plain per-instance flake path).
pub fn removeCompositionFlake(allocator: std.mem.Allocator, io: std.Io, dir: []const u8) !void {
	const cwd = std.Io.Dir.cwd();
	for ([_][]const u8{ "flake.nix", "flake.nix.tmp", "flake.lock" }) |f| {
		const path = try std.fs.path.join(allocator, &.{ dir, f });
		defer allocator.free(path);
		cwd.deleteFile(io, path) catch {};
	}
}
